
```{r, echo = FALSE, message = FALSE}
source("../scripts/setup.R")
```


# Conclusion 
Given the context of this series, we could have expected a much more scientific vocabulary. But we realized that it fits a lot in the codes of American sitcoms that puts forward the relationships between the characters, the dramas, and the typical subjects that we can expect from people of their age. 

The second half of the show seems more positive score. We can suppose that the characters tend to become more positive and maybe less sarcastic as the series goes on.

Concerning the characters, Sheldon is the star of the show and this is felt in the analysis. He is always the one who talks the most and is the most intense.

The second half of the show, except for season 7, has a more positive score. We can suppose that the characters tend to become more positive and maybe less sarcastic as the series goes on. 

# Limits:
Some limits we encountered, could be : 

- maybe a problems in web-scrapping for season 2 and 6 as they seems to be shorter in terms of the number of words web-scrapped.
- a non-exhaustive list of the characters of the series, which can differ a little bit the exploratory analysis

# Futur work: 
As a future work, we might want to improve the Machine Learning part. Indeed, as already explained, the accuracy is not very large so we could try to find new techniques to improve or even try other machine learning model. Another aspect could be to continue the part we started about the prediction of a character based on a given sentence. 







